services:
  # An old issue: docker-compose will mount volume as root.
  # Workaround: https://github.com/docker/compose/issues/3270
  # (Command 'docker run -v' is not affected)
  file-chown:
    container_name: file-chown
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot"
    user: "root"
    volumes: 
      - "./storage:/home/runner"
    command: "chown -R runner:runner /home/runner"

  comfyui-0:
    init: true
    container_name: comfyui-0
    depends_on:
      file-chown:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot"
    ports:
      - "8188:8188"
      - "8192:8189"
    volumes:
      - "./storage:/home/runner"
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  comfyui-1:
    init: true
    container_name: comfyui-1
    depends_on:
      file-chown:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot"
    ports:
      - "8191:8188"
      - "8193:8189"
    volumes:
      - "./storage:/home/runner"
    environment:
      - CLI_ARGS=
    security_opt:
      - "label=type:nvidia_container_t"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
